version: '2'
services:
    cella-app:
        image: cella
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cella-mysql:3306/cella?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8079:8079
    cella-mysql:
        extends:
            file: mysql.yml
            service: cella-mysql
